# Generated by Django 4.2 on 2023-05-01 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="simple one-line text.",
                        max_length=100,
                        verbose_name="DESCRIPTION",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="TITLE")),
                ("request", models.CharField(max_length=20, verbose_name="Request")),
                ("price1", models.CharField(max_length=20, verbose_name="Price1")),
                (
                    "price2",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Price2"
                    ),
                ),
                (
                    "price3",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Price3"
                    ),
                ),
                ("kind", models.CharField(max_length=20, verbose_name="Kind")),
                ("spec", models.CharField(max_length=50, verbose_name="Spec")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="simple one-line text.",
                        max_length=100,
                        null=True,
                        verbose_name="DESCRIPTION",
                    ),
                ),
                (
                    "agent",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Agent"
                    ),
                ),
                ("register", models.CharField(max_length=30, verbose_name="Register")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/%Y/%m/",
                        verbose_name="IMAGE",
                    ),
                ),
                (
                    "image1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/%Y/%m/",
                        verbose_name="IMAGE1",
                    ),
                ),
                ("content", models.TextField(verbose_name="CONTENT")),
                (
                    "like",
                    models.PositiveSmallIntegerField(default=0, verbose_name="LIKE"),
                ),
                (
                    "create_dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="CREATE DT"),
                ),
                (
                    "update_dt",
                    models.DateTimeField(auto_now=True, verbose_name="UPDATE DT"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="blog.category",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="blog.tag")),
            ],
            options={"ordering": ("update_dt",),},
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="CONTENT")),
                (
                    "create_dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="CREATE DT"),
                ),
                (
                    "update_dt",
                    models.DateTimeField(auto_now=True, verbose_name="UPDATE DT"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.post",
                    ),
                ),
            ],
        ),
    ]
